#!/bin/bash

cache_file="$HOME/.cache/via"

reload_cache_file() {
	cat "$HOME/.config/via/shortcuts" > "$cache_file"
	cat "$HOME/.config/via/websites" >> "$cache_file"
	find "$HOME" -mindepth 1 \( -name ".*" -o -path "$HOME/code/*" \) -prune -o -print | sort >> "$cache_file"
}

output_feed() {
  feed_list="$cache_file"
  system="$OSTYPE"

  if [ "$system" == "linux-gnu"* ], then
    wmctrl -xl | sed "s/^[^.]*\.//;s/ \+\S\+ \+/ /;s/^/w /;s/ \+/ /g"
  fi

  cat "$feed_list"
}

if [[ "$1" == "-r" ]] || [[ ! -f "$cache_file" ]]; then
  reload_cache_file
fi

output_feed
